Issue #2763075 by raman.b, Martijn de Wit, anon, borisson_: Adding new text format gives Uncaught TypeError: f.format_tags.split is not a function
(cherry picked from commit 190aae107947f7e40963a25affc16d9daec0f6fd)